First articles
makovstanislav/blog pull request #3
Opened 2022-06-01 21:28 UTC by makovstanislav

without cs

2022-06-02 11:33 UTC, anatoliykmetyuk commented on gatsby-config.js
>      siteUrl: `https://www.akmetiuk.com`,
Это нужно будет поменять как домен будет

2022-06-07 20:06 UTC, anatoliykmetyuk requested changes
`cs` файл опять появился. Добавь в гитигнор.

2022-06-07 20:06 UTC, anatoliykmetyuk commented on gatsby-config.js
>      siteUrl: `https://www.akmetiuk.com`,
Это нужно будет поменять как домен будет.

2022-06-07 20:06 UTC, anatoliykmetyuk commented on gatsby-config.js
> +    facebook: "1806mk",
Не уверен, подберёт ли гатсби Фейсбук, нужно чекать.

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +* entry-level programming knowledge
```suggestion
* Entry-level programming knowledge
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +If you are an experienced developer I`d recommend starting with **[Scala 3 Book](https://docs.scala-lang.org/scala3/book/introduction.html)**.
```suggestion
If you are an experienced developer I'd recommend starting with **[Scala 3 Book](https://docs.scala-lang.org/scala3/book/introduction.html)**. 
```

` используется для подсветки кода в маркдауне, используй ' в качестве апострофа для избежания конфликтов. Проверь свои статьи на другие такие апострофы.

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +Install **[VS Code](https://code.visualstudio.com)**. You may choose another editor: Sublime Text, Vim or Emacs. Each of them is lightweight and beloved by community. The other cool way of editing Sc
```suggestion
Install **[VS Code](https://code.visualstudio.com)**. You may choose another editor: Sublime Text, Vim or Emacs. Each of them is lightweight and beloved by the community. The other way of working with the Scala code is using **[Intellij IDEA](https://www.jetbrains.com/help/idea/discover-intellij-idea-for-scala.html)**. Still, for immediate immersion to Scala, we stick with VS Code. 
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +Install **[VS Code](https://code.visualstudio.com)**. You may choose another editor: Sublime Text, Vim or Emacs. Each of them is lightweight and beloved by community. The other cool way of editing Sc
Хорошей идеей будет прогнать статью через Граммарли.

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +This plugin enriches the editor with understanding of Scala code. As a result, the editor enhances your development experience. For instance, it highlights syntax errors, autocompletes code (kind of
```suggestion
This plugin teaches the editor to understand the Scala code. As a result, the editor enhances your development experience. For instance, it highlights syntax errors, autocompletes code (kind of T9) or keeps indentation. If you do not install the extension, you still be able to write in Scala but an editor won't know how to assist you.
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> + Install a default set of applications allowing Scala program to run. Just insert the following in Terminal:
```suggestion
Install a default set of applications needed for a Scala program to run. Just insert the following in the Terminal:
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +   curl -fL https://github.com/coursier/launchers/raw/master/cs-x86_64-apple-darwin.gz | gzip -d > cs && chmod +x cs && (xattr -d com.apple.quarantine cs || true) && ./cs setup
Эта команда может устареть. Будет хорошо дать линк вместе с командой на то, откуда ты ее взял. Например в сносках (погугли markdown footnotes либо Gatsby footnotes).

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +   <img src="/post_assets/2022-05-14-creating-first-application/cs-setup.gif" width="600" height="400">
Отличная идея с гифками!

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +This command launches the application called Coursier that installs the bundle. As a whole, these apps consist typical Scala development environment. The list of the them can be found **[here](https:
```suggestion
This command launches the application called Coursier that installs the required software. This software constitutes the basis of the Scala development environment. The list of the them can be found **[here](https://get-coursier.io/docs/cli-installation)**. If you are looking for other ways to setup the Scala development environment, e.g. using Brew, see  [Coursier documentation](https://get-coursier.io/docs/cli-installation). 
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +Lets check if the installation has been successful. Run ```scala -version``` in Terminal. Once it outputs Scala version and year, everything is fine
```suggestion
Let's verify that the installation has been successful. Run `scala -version` in the Terminal. If the installation was successful, you should see the Scala version in the output.
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +Lets check if the installation has been successful. Run ```scala -version``` in Terminal. Once it outputs Scala version and year, everything is fine
Let's = let us
Lets - глагол (this program lets you compile Scala)

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +If you do not receive the needed output, please reboot the computer 💻
Не поможет ребут скорее всего :) лучше это убрать.

```suggestion
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +Perfect. One of the coolest programming language is ready to use 👌
```suggestion
Perfect. One of the coolest programming languages is ready for use 👌
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +####
```suggestion
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +"Create a project" implies to generate a folder containing source files of your program. For this purpose,
```suggestion
"Create a project" implies generating a folder containing the source files of your program. For this purpose, 
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +2. Open the created folder with Terminal. You can do it either by tapping "New Terminal at Folder" or, in case you are familiar with Terminal, cd to the folder.
```suggestion
2. Open the created folder with the terminal. You can do it either by right-clicking on the folder and selecting "New Terminal at Folder", or, in case you are familiar with the terminal, `cd` to the folder.
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +2. Run command ```sbt```. We have just started so-called "sbt server". Now it is accepting (listening and implementing) input from Terminal.
```suggestion
2. Run the `sbt` command. We have just started a so-called "sbt server". Now it is accepting (listening and  interpreting) input from the Terminal.
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +Your first Scala 3 application has been runned successfully.
```suggestion
Your first Scala 3 application has run successfully.
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-15-environment-overview.md
> +|**Sbt** |Build automation tool. In full form: "scala build tool"| It builds Scala project automatically and exploits various apps to run Scala code. Consider it as a coordinator.|Go to the project f
Ты уверен на счёт "Scala build tool"? Вроде было "simple build tool".

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-15-environment-overview.md
> +|**Ammonite**|	Enhanced Scala REPL and script runner| Evaluates expressions written in Scala |	By CLI when you want to run (e.g. test) easily some script without the overhead of setting up a project.
Хорошее понимание концепций👍

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-16-what-happens-during-launching.md
> +<br>Let's explore what happens once we`ve typed ```$sbt run``` in Terminal.</br>
```suggestion
<br>Let's explore what happens once we`ve typed `$sbt run` in Terminal.</br>
```

Три апострофа нужны только когда код начинается с новой строки. Если код в предложении, ставь один апостроф.

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-16-what-happens-during-launching.md
> +Source code is stored in .scala files. Now we also have .class files. They are regular Java class files containing Java bytecode to be executed by the Java Virtual Machine (JVM). By default, scalac g
```suggestion
Source code is stored in .scala files.  After the compilation we also have .class files. They are regular Java class files containing Java bytecode to be executed by the Java Virtual Machine (JVM). By default, scalac generates the class files into the current working directory. 
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-16-what-happens-during-launching.md
> +Currently, there is the program bytecode stored in .class files in a separate folder and understandable to the machine.
```suggestion
```
Повторяешь предыдущий параграф.

2022-06-07 20:06 UTC, anatoliykmetyuk commented on src/components/layout.js
> +        <title>How to use Scala 3</title>
Это название будет отображаться на главной страничке блога.

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +Install **[VS Code](https://code.visualstudio.com)**. You might choose another editor: Sublime Text, Vim or Emacs. Each of them is lightweight and beloved by the community. The other excellent way of
Лучше не упоминай IntelliJ. Пока что поддержка Скала 3 там оставляет желать лучшего, Getting Started на официальном сайте устарел и будет переделан.

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +This plugin enriches the editor with an understanding of Scala code. As a result, the editor enhances your development experience. For instance, it highlights syntax errors, autocompletes code (kind
Т9 не очень аналогия, древняя технология. Можно упомянуть, что современные телефоны выдают подсказки при печати на своих клавиатурах.

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +This command launches the application called Coursier that installs the bundle. As a whole, these apps consist typical Scala development environment. The list of them can be found **[here](https://ge
```suggestion
This command launches the application called Coursier that installs the bundle. As a whole, these apps constitute a typical Scala development environment. The list of them can be found **[here](https://get-coursier.io/docs/cli-installation)**. If you are looking for other ways to set up Scala development environment, e.g. using Homebrew, see  [Coursier documentation](https://get-coursier.io/docs/cli-installation). 
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +Let's check if the installation has been successful. Run ```scala -version``` in Terminal. Once it outputs Scala version and year, everything is fine:
```suggestion
Let's check if the installation has been successful. Run ```scala -version``` in the terminal. Once it outputs Scala version and year, everything is fine:
```

"Terminal" – это не одна программа, а интерфейс для отправки компьютеру команд на выполнение. Существует много программ, которые предоставляют пользователю этот интерфейс, одна из них называется "Terminal" и идет по дефолту с маком.

Исправь другие такие упоминания.

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +title: Creating first application
```suggestion
title: Creating the first application
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +Perfect. One of the coolest programming languages is ready to use 👌
```suggestion
Perfect. One of the coolest programming languages is ready for use 👌
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +1. Create an empty folder on your computer manually. Feel free to name and locate it for your consideration.
```suggestion
1. Create an empty folder on your computer manually. Feel free to name and locate it at your discretion.
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +3. Once you`ve selected and clicked “Open”, VS Code will start opening the project and ask you whether to import the build. Press “Import build”.
```suggestion
3. Once you`ve selected and clicked “Open”, VS Code will start opening the project and will ask you whether to import the build. Press “Import build”.
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +
Четыре новых линии подряд. Убери во всех статьях лишние новые линии.

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +2. Run command ```sbt```. We have just started the so-called "sbt server". Now it is accepting (listening and implementing) input from Terminal.
```suggestion
2. Run command `sbt`. We have just started the so-called "sbt server". Now it is accepting (listening and implementing) input from Terminal.
```

Когда пишешь код в предложении, можно использовать один апостроф. Три апострофа нужны когда у тебя блок кода. Поправь везде.

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-14-creating-first-application.md
> +
Много новый линий в конце файлов.

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-15-environment-overview.md
> +This article breaks down typical Scala development environment. We installed it in the previous section.
```suggestion
This article breaks down a typical Scala development environment that we installed in the previous section.
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-15-environment-overview.md
> +|**Metals**|	Extention for VS Code. Language server for Scala. |	It powers editing experience by error-checking, code formatting, autocompletion etc. Without it, the editor would not know how to assi
```suggestion
|**Metals**|	Extention for VS Code. Language server for Scala. |	It powers editing experience by error-checking, code formatting, autocompletion etc. Without it, the editor would not know how to assist you. Though it`s not an IDE, it has rich IDE features.	| After you install the extension, the editor will automatically use it.|
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-15-environment-overview.md
> +|**Coursier**|Scala development environment installer.  Artefacts fetcher (or "dependency resolver")| It automatically installs applications and fetches other resources allowing Scala program to run.
```suggestion
|**Coursier**|Scala development environment installer.  Artefacts fetcher (or "dependency resolver")| It automatically installs applications and fetches other resources allowing Scala programs to run.| It is used from the terminal by the user to install Scala.|
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-15-environment-overview.md
> +|**Sbt** |Build automation tool. In full form: "scala build tool"| It builds Scala projects automatically and exploits various apps to run Scala code. Consider it as a coordinator.|Go to the project
```suggestion
|**Sbt** |Build automation tool. Stands for "scala build tool"| It builds and runs Scala projects while interfacing with other applications. Consider it as a coordinator of those applications.|Go to the project folder via the terminal and type `sbt`. |
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-15-environment-overview.md
> +|**Scalac**|Scala compiler|It converts Scala code into Java bytecode so that a virtual machine can read it and run.|Sbt launches Scalac automatically (under the hood) when you run your program by sbt
```suggestion
|**Scalac**|Scala compiler|It converts Scala code into Java bytecode so that the Java Virtual Machine (JVM) can run it.|Sbt launches Scalac when you compile your program. Compilation is done before running the program when you execute the `run` command from sbt.|
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-15-environment-overview.md
> +|**JVM** |Java Virtual Machine. Not the Java programming language|Runs Java bytecode. Note: firstly, Scalac compiles (converts) Scala code into Java bytecode, and then JVM runs the bytecode. |Sbt lau
```suggestion
|**JVM** |Java Virtual Machine. Distinguish from the Java programming language|Runs Java bytecode. Note: first, Scalac compiles (converts) Scala code into Java bytecode, and then the JVM runs the bytecode. |Sbt launches JVM automatically (under the hood) when you run your program by sbt.|
```

"the JVM", та же ситуация, что и в случае с "the terminal". JVM – это не программа, а спецификация программы. Существует много реализаций этой спецификации.

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-15-environment-overview.md
> +|**Adopt Open JDK**|Java development kit (it includes standard Java libraries, Java compiler, debugger and many more components)|It facilitates applications creation on Java platform.|There is no muc
```suggestion
|**JDK**|Java development kit (it includes the standard Java libraries, the Java compiler, a debugger and many more components)|It facilitates applications creation for the Java platform.|There is no need for the programmer to use the applications of the JDK manually. Sbt launches them automatically when you run your program.|
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-15-environment-overview.md
> +|**Scala**| Scala REPL and script runner| Evaluates expressions written in Scala. |	By CLI when you want to run (e.g. test) easily some script without the overhead of setting up a project. Kind of "p
Не только REPL и script runner. Так же используется для запуска скомпилированных скала программ – *.class файлов. Для этого, команда `scala` вызывает `java`, таким образом передавая байткод на JVM для выполнения. Команда `java` не может быть использована напрямую для выполнения скала программ так как ей нужно знать, где находятся стандартная библиотека скала (Scala standard library). `scala` предоставляет `java` эту информацию.

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-15-environment-overview.md
> +|**Ammonite**|	Enhanced Scala REPL and script runner| Evaluates expressions written in Scala |	By CLI when you want to run (e.g. test) easily some script without the overhead of setting up a project.
```suggestion
|**Ammonite**|	Enhanced Scala REPL and script runner| Evaluates expressions written in Scala |	Is launched from the terminal when you want to run easily (e.g. for testing purposes) some script without the overhead of setting up a project. Kind of "playground area".	|
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-16-what-happens-during-launching.md
> +title: What happens during launching?
```suggestion
title: What happens during launch?
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-16-what-happens-during-launching.md
> +description: This articles explains sequence of program execution
```suggestion
description: This article explains the sequence of program execution
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-16-what-happens-during-launching.md
> +In essence, the process of launching the program consists of compilation and execution. In our case, we need to convert Scala code into Java bytecode and execute the result on Java Virtual Machine.
```suggestion
In essence, the process of launching the program consists of compilation and execution. In our case, we need to convert Scala code into Java bytecode and execute the result on the Java Virtual Machine. 
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-16-what-happens-during-launching.md
> +So that not to launch these processes manually, we usually use sbt application, which calls different programs. <br>Let's explore what happens once we`ve typed ```$sbt run``` in Terminal.</br>
```suggestion
So that not to perform these actions manually, we usually use sbt, which calls different programs. <br>Let's explore what happens once we`ve typed ```sbt run``` in Terminal.</br>
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-16-what-happens-during-launching.md
> +- sbt calls Scala compiler (scalac)
```suggestion
- sbt calls the Scala compiler (scalac)
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-16-what-happens-during-launching.md
> +- scalac converts Scala source code into Java bytecode
```suggestion
- scalac converts the Scala source code into the Java bytecode
```

Добавь везде артикли перед "Scala code" и "Java bytecode".

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-16-what-happens-during-launching.md
> +Source code is stored in .scala files. Now we have .class files additionally. They are regular Java class files containing Java bytecode to be executed by the Java Virtual Machine (JVM). By default,
```suggestion
The source code is stored in `.scala` files. After the compilation, we get also the `.class` files. They are regular Java class files containing Java bytecode to be executed by the Java Virtual Machine (JVM). By default, scalac generates the class files into the current working directory. 
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-16-what-happens-during-launching.md
> +Let's fix our current state: the program bytecode is stored in .class files in a separate folder and understandable to the machine.
Эта строчка лишняя, не несет дополнительной информации.

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-16-what-happens-during-launching.md
> +## Step 2: Running
```suggestion
## Step 2: Execution
```

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-16-what-happens-during-launching.md
> +- once the files have been compiled, sbt calls Scala
```suggestion
- once the files have been compiled, sbt calls `scala`
```

`scala` – команда, Scala – язык.

2022-06-07 20:06 UTC, anatoliykmetyuk commented on posts/2022-05-16-what-happens-during-launching.md
> +As we have learned, we just need to type ```$sbt run```  in CLI and sbt will take care of the rest.
```suggestion
As we have learned, we just need to type `sbt run`  in CLI and sbt will take care of the rest.
```

2022-06-07 20:10 UTC, makovstanislav commented on gatsby-config.js
> +    facebook: "1806mk",
Чекнул - работает

2022-06-07 20:12 UTC, makovstanislav commented on posts/2022-05-14-creating-first-application.md
> +Install **[VS Code](https://code.visualstudio.com)**. You may choose another editor: Sublime Text, Vim or Emacs. Each of them is lightweight and beloved by community. The other cool way of editing Sc
Этот  текст уже проверен Граммарли) Возможно, платная версия лучше правит

2022-06-07 20:15 UTC, makovstanislav commented on posts/2022-05-14-creating-first-application.md
> + Install a default set of applications allowing Scala program to run. Just insert the following in Terminal:
"allowing", кстати, взято из оф документации)

2022-06-07 20:15 UTC, makovstanislav commented on posts/2022-05-14-creating-first-application.md
> +   curl -fL https://github.com/coursier/launchers/raw/master/cs-x86_64-apple-darwin.gz | gzip -d > cs && chmod +x cs && (xattr -d com.apple.quarantine cs || true) && ./cs setup
Хорошая идея

2022-06-07 20:18 UTC, makovstanislav commented on posts/2022-05-14-creating-first-application.md
> +If you do not receive the needed output, please reboot the computer 💻
Лично столкнулся с такой проблемой) Ребут помог

2022-06-07 20:21 UTC, makovstanislav commented on posts/2022-05-15-environment-overview.md
> +|**Sbt** |Build automation tool. In full form: "scala build tool"| It builds Scala project automatically and exploits various apps to run Scala code. Consider it as a coordinator.|Go to the project f
Ты прав, я взял из ненадежного источника

2022-06-11 11:00 UTC, merged